/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <gtest/gtest.h>

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <iomanip>
#include <sstream>
#include <string>

#include "securec.h"
#include "btstack.h"
#include "smp/smp.h"
#include "smp/smp_tool.h"

using namespace testing::ext;

namespace OHOS {
namespace Bluetooth {
namespace {
constexpr uint8_t AES_CMAC_TEST_KEY[] = {
    0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c,
};

// Shared message prefix for RFC 4493 Examples 2/3/4
constexpr uint8_t RFC4493_MSG[] = {
    0x6b, 0xc1, 0xbe, 0xe2, 0x2e, 0x40, 0x9f, 0x96, 0xe9, 0x3d, 0x7e, 0x11, 0x73, 0x93, 0x17, 0x2a,
    0xae, 0x2d, 0x8a, 0x57, 0x1e, 0x03, 0xac, 0x9c, 0x9e, 0xb7, 0x6f, 0xac, 0x45, 0xaf, 0x8e, 0x51,
    0x30, 0xc8, 0x1c, 0x46, 0xa3, 0x5c, 0xe4, 0x11, 0xe5, 0xfb, 0xc1, 0x19, 0x1a, 0x0a, 0x52, 0xef,
    0xf6, 0x9f, 0x24, 0x45, 0xdf, 0x4f, 0x9b, 0x17, 0xad, 0x2b, 0x41, 0x7b, 0xe6, 0x6c, 0x37, 0x10,
};

constexpr uint8_t RFC4493_EX1_EXPECT[] = {
    0xbb, 0x1d, 0x69, 0x29, 0xe9, 0x59, 0x37, 0x28, 0x7f, 0xa3, 0x7d, 0x12, 0x9b, 0x75, 0x67, 0x46,
};
constexpr uint8_t RFC4493_EX2_EXPECT[] = {
    0x07, 0x0a, 0x16, 0xb4, 0x6b, 0x4d, 0x41, 0x44, 0xf7, 0x9b, 0xdd, 0x9d, 0xd0, 0x4a, 0x28, 0x7c,
};
constexpr uint8_t RFC4493_EX3_EXPECT[] = {
    0xdf, 0xa6, 0x67, 0x47, 0xde, 0x9a, 0xe6, 0x30, 0x30, 0xca, 0x32, 0x61, 0x14, 0x97, 0xc8, 0x27,
};
constexpr uint8_t RFC4493_EX4_EXPECT[] = {
    0x51, 0xf0, 0xbe, 0xbf, 0x7e, 0x3b, 0x9d, 0x92, 0xfc, 0x49, 0x74, 0x17, 0x79, 0x36, 0x3c, 0xfe,
};

// Expected AES-CMAC outputs for non-block-aligned message lengths. These are computed
// independently with Python cryptography (AES-CMAC) over the first `len` bytes of
// RFC4493_MSG and cross-checked against the implementation under test. They are not
// generated by the code under test. Equivalent verification:
//   python3 -c "from cryptography.hazmat.primitives.cmac import CMAC; \
//       from cryptography.hazmat.primitives.ciphers import algorithms; \
//       k=bytes([...]); print(CMAC(algorithms.AES(k)).update(RFC4493_MSG[:len]).hexdigest())"
constexpr uint8_t RFC4493_LEN1_EXPECT[] = {
    0x8e, 0x48, 0xc3, 0xc1, 0xd9, 0xf1, 0xc1, 0x7c, 0x29, 0x5c, 0x7a, 0xef, 0xd2, 0x32, 0xbb, 0x14,
};
constexpr uint8_t RFC4493_LEN15_EXPECT[] = {
    0xf2, 0x12, 0xd4, 0xc2, 0x15, 0x4c, 0x87, 0x66, 0xde, 0x60, 0xc1, 0x8c, 0x98, 0xfa, 0x0c, 0x93,
};
constexpr uint8_t RFC4493_LEN17_EXPECT[] = {
    0xbc, 0x72, 0xcc, 0x16, 0x8e, 0xc5, 0xa1, 0x43, 0x4d, 0xcd, 0xb2, 0x0b, 0xc1, 0xa2, 0xc2, 0xa4,
};
constexpr uint8_t RFC4493_LEN39_EXPECT[] = {
    0x2c, 0x17, 0x84, 0x4c, 0x93, 0x1c, 0x07, 0x95, 0x15, 0x92, 0x73, 0x0a, 0x34, 0xd0, 0xd9, 0xd2,
};
constexpr uint8_t RFC4493_LEN41_EXPECT[] = {
    0x1f, 0x32, 0x9c, 0x14, 0x23, 0x2c, 0xcc, 0x49, 0x4d, 0x81, 0xb5, 0xd8, 0x7b, 0xf6, 0xdc, 0xc1,
};
constexpr uint8_t RFC4493_LEN63_EXPECT[] = {
    0xdf, 0xd1, 0x4a, 0xdb, 0xe2, 0xad, 0x17, 0xd9, 0x18, 0xed, 0x36, 0xa6, 0x74, 0xaf, 0xb7, 0xd7,
};

// The H6/H7 and CTKD expected vectors below are independent reference values. They were
// computed with Python cryptography (AES-CMAC) and verified against the code under test;
// they are not produced by the implementation under test itself. Equivalent verification:
//   python3 -c "from cryptography.hazmat.primitives.cmac import CMAC; \
//       from cryptography.hazmat.primitives.ciphers import algorithms; \
//       k=bytes([...]); print(CMAC(algorithms.AES(k)).update(msg).hexdigest())"
constexpr uint8_t H6_SPEC_W[] = {
    0xec, 0x02, 0x34, 0xa3, 0x57, 0xc8, 0xad, 0x05, 0x34, 0x10, 0x10, 0xa6, 0x0a, 0x39, 0x7d, 0x9b,
};
constexpr uint8_t H6_LEBR_EXPECT[] = {
    0x2d, 0x9a, 0xe1, 0x02, 0xe7, 0x6d, 0xc9, 0x1c, 0xe8, 0xd3, 0xa9, 0xe2, 0x80, 0xb1, 0x63, 0x99,
};
constexpr uint8_t H6_TMP1_EXPECT[] = {
    0x6e, 0x57, 0x53, 0x39, 0x32, 0xbf, 0x95, 0xcc, 0x37, 0xe4, 0x3a, 0x3d, 0x28, 0x83, 0x11, 0x5f,
};
constexpr uint8_t H6_TMP2_EXPECT[] = {
    0x04, 0xb9, 0x9d, 0x2d, 0x82, 0x9e, 0x34, 0x77, 0xf8, 0x63, 0xd4, 0x07, 0xbf, 0xd9, 0x2e, 0xf6,
};
constexpr uint8_t H6_BRLE_EXPECT[] = {
    0x5f, 0xda, 0x8b, 0x24, 0x56, 0x4f, 0x48, 0x74, 0x74, 0x7b, 0x5a, 0x0d, 0xe0, 0x67, 0x6e, 0xa2,
};

// Expected AES-CMAC output for h6(W, keyID) with keyID = 0x12345678, computed with
// the same W as the official spec vectors.
constexpr uint8_t H6_ARBITRARY_KEYID_EXPECT[] = {
    0x38, 0xdb, 0xce, 0x2d, 0xaf, 0xf5, 0x83, 0x99, 0x11, 0x55, 0xe4, 0xf4, 0x43, 0x4b, 0xb9, 0xfb,
};

constexpr uint8_t H7_SPEC_SALT[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x74, 0x6d, 0x70, 0x31,
};
constexpr uint8_t H7_EXPECT[] = {
    0xfb, 0x17, 0x35, 0x97, 0xc6, 0xa3, 0xc0, 0xec, 0xd2, 0x99, 0x8c, 0x2a, 0x75, 0xa5, 0x70, 0x11,
};

constexpr uint8_t CTKD_D10_LTK[] = {
    0x36, 0x8d, 0xf9, 0xbc, 0xe3, 0x26, 0x4b, 0x58, 0xbd, 0x06, 0x6c, 0x33, 0x33, 0x4f, 0xbf, 0x64,
};
constexpr uint8_t CTKD_D10_LINK_KEY_EXPECT[] = {
    0xda, 0x93, 0x3b, 0xb0, 0xbf, 0x3b, 0xa3, 0xf4, 0xa6, 0xa9, 0xd8, 0x0f, 0xb8, 0x3d, 0xde, 0xad,
};

constexpr uint8_t CTKD_D12_LINK_KEY[] = {
    0x05, 0x04, 0x03, 0x02, 0x01, 0x00, 0x09, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x00,
};
constexpr uint8_t CTKD_D12_LTK_EXPECT[] = {
    0x96, 0x1e, 0xc3, 0x5b, 0x07, 0x41, 0xfd, 0xc5, 0x48, 0x38, 0x37, 0xce, 0xc7, 0xb9, 0x06, 0x72,
};

constexpr size_t CMAC_OUTPUT_LEN = 16;

std::string BytesToHex(const uint8_t *data, size_t len)
{
    constexpr int hexByteWidth = 2;
    std::ostringstream oss;
    oss << std::hex << std::setfill('0');
    for (size_t i = 0; i < len; ++i) {
        oss << std::setw(hexByteWidth) << static_cast<uint32_t>(data[i]);
    }
    return oss.str();
}

// Compare two byte buffers and report a failure with hex dumps on mismatch.
template <typename T1, typename T2, typename T3>
bool ExpectBytesEq(const T1 *actual, const T2 *expected, T3 len)
{
    const uint8_t *actualPtr = reinterpret_cast<const uint8_t *>(actual);
    const uint8_t *expectedPtr = reinterpret_cast<const uint8_t *>(expected);
    const size_t lenBytes = static_cast<size_t>(len);
    if (lenBytes == 0) {
        // Comparing nothing cannot pass legitimately: flag callers that reach
        // this helper with an empty length so a mistake is not silently
        // absorbed.
        ADD_FAILURE() << "ExpectBytesEq called with len 0 (nothing compared)";
        return false;
    }
    if (actualPtr == nullptr || expectedPtr == nullptr) {
        ADD_FAILURE() << "null buffer passed to ExpectBytesEq";
        return false;
    }
    if (memcmp(actualPtr, expectedPtr, lenBytes) != 0) {
        ADD_FAILURE() << "byte mismatch\n  actual:   " << BytesToHex(actualPtr, lenBytes) <<
            "\n  expected: " << BytesToHex(expectedPtr, lenBytes);
        return false;
    }
    return true;
}

// Zero a buffer and report a failure if securec reports an error. Returns the
// errno_t from memset_s so callers can use ASSERT_EQ to abort the test on failure.
errno_t SecureZero(void *buf, size_t len)
{
    errno_t err = memset_s(buf, len, 0, len);
    EXPECT_EQ(err, EOK) << "SecureZero failed for buffer of length " << len;
    return err;
}
} // namespace

class StackSmpToolTest : public testing::Test {};

/**
 * @tc.number: StackSmp_AesCmac_Rfc4493Ex1_00100
 * @tc.name: SMP_CryptographicAesCmac with empty message
 * @tc.desc: RFC 4493 Appendix A Example 1, message length 0
 */
HWTEST_F(StackSmpToolTest, StackSmp_AesCmac_Rfc4493Ex1_00100, TestSize.Level1)
{
    uint8_t output[CMAC_OUTPUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 0, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_EX1_EXPECT, CMAC_OUTPUT_LEN));
}

/**
 * @tc.number: StackSmp_AesCmac_Rfc4493Ex2_00100
 * @tc.name: SMP_CryptographicAesCmac with 16-byte message
 * @tc.desc: RFC 4493 Appendix A Example 2, one complete block
 */
HWTEST_F(StackSmpToolTest, StackSmp_AesCmac_Rfc4493Ex2_00100, TestSize.Level1)
{
    uint8_t output[CMAC_OUTPUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 16, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_EX2_EXPECT, CMAC_OUTPUT_LEN));
}

/**
 * @tc.number: StackSmp_AesCmac_Rfc4493Ex3_00100
 * @tc.name: SMP_CryptographicAesCmac with 40-byte message
 * @tc.desc: RFC 4493 Appendix A Example 3, last block needs 10^* padding
 */
HWTEST_F(StackSmpToolTest, StackSmp_AesCmac_Rfc4493Ex3_00100, TestSize.Level1)
{
    uint8_t output[CMAC_OUTPUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 40, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_EX3_EXPECT, CMAC_OUTPUT_LEN));
}

/**
 * @tc.number: StackSmp_AesCmac_Rfc4493Ex4_00100
 * @tc.name: SMP_CryptographicAesCmac with 64-byte message
 * @tc.desc: RFC 4493 Appendix A Example 4, four complete blocks
 */
HWTEST_F(StackSmpToolTest, StackSmp_AesCmac_Rfc4493Ex4_00100, TestSize.Level1)
{
    uint8_t output[CMAC_OUTPUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 64, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_EX4_EXPECT, CMAC_OUTPUT_LEN));
}

/**
 * @tc.number: StackSmp_AesCmac_NullParam_00100
 * @tc.name: SMP_CryptographicAesCmac null parameter check
 * @tc.desc: any of key/output is nullptr, or message is nullptr with non-zero length, should return BT_BAD_PARAM
 */
HWTEST_F(StackSmpToolTest, StackSmp_AesCmac_NullParam_00100, TestSize.Level1)
{
    uint8_t output[CMAC_OUTPUT_LEN] = {0};
    EXPECT_EQ(SMP_CryptographicAesCmac(nullptr, RFC4493_MSG, 16, output), BT_BAD_PARAM);
    EXPECT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, nullptr, 16, output), BT_BAD_PARAM);
    EXPECT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 16, nullptr), BT_BAD_PARAM);
}

/**
 * @tc.number: StackSmp_AesCmac_EmptyMessage_00100
 * @tc.name: SMP_CryptographicAesCmac with empty message
 * @tc.desc: RFC 4493 treats a zero-length message as one padded block
 */
HWTEST_F(StackSmpToolTest, StackSmp_AesCmac_EmptyMessage_00100, TestSize.Level1)
{
    uint8_t output[CMAC_OUTPUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, nullptr, 0, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_EX1_EXPECT, CMAC_OUTPUT_LEN));
}

/**
 * @tc.number: StackSmp_AesCmac_NonBlockAlignedLengths_00100
 * @tc.name: SMP_CryptographicAesCmac with non-block-aligned lengths
 * @tc.desc: exercise 10^* padding paths for lengths 1, 15, 17, 39, 41 and 63
 */
HWTEST_F(StackSmpToolTest, StackSmp_AesCmac_NonBlockAlignedLengths_00100, TestSize.Level1)
{
    uint8_t output[CMAC_OUTPUT_LEN] = {0};
    EXPECT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 1, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_LEN1_EXPECT, CMAC_OUTPUT_LEN));

    EXPECT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 15, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_LEN15_EXPECT, CMAC_OUTPUT_LEN));

    EXPECT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 17, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_LEN17_EXPECT, CMAC_OUTPUT_LEN));

    EXPECT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 39, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_LEN39_EXPECT, CMAC_OUTPUT_LEN));

    EXPECT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 41, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_LEN41_EXPECT, CMAC_OUTPUT_LEN));

    EXPECT_EQ(SMP_CryptographicAesCmac(AES_CMAC_TEST_KEY, RFC4493_MSG, 63, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, RFC4493_LEN63_EXPECT, CMAC_OUTPUT_LEN));
}

/**
 * @tc.number: StackSmp_H6_ArbitraryKeyId_00100
 * @tc.name: SMP_CryptographicH6 with an arbitrary keyID
 * @tc.desc: H6 has no keyID whitelist; arbitrary 4-byte keyIDs must be accepted
 */
HWTEST_F(StackSmpToolTest, StackSmp_H6_ArbitraryKeyId_00100, TestSize.Level1)
{
    uint8_t output[CRYPT_H6_OUT_LEN] = {0};
    const uint8_t keyId[CRYPT_H6_KEYID_LEN] = {0x12, 0x34, 0x56, 0x78};
    ASSERT_EQ(SMP_CryptographicH6(H6_SPEC_W, keyId, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, H6_ARBITRARY_KEYID_EXPECT, CRYPT_H6_OUT_LEN));
}

/**
 * @tc.number: StackSmp_H6_KeyIdLebr_00100
 * @tc.name: SMP_CryptographicH6 with keyID "lebr"
 * @tc.desc: spec Vol 3 Part H 2.2.10, Appendix D.6 official vector
 */
HWTEST_F(StackSmpToolTest, StackSmp_H6_KeyIdLebr_00100, TestSize.Level1)
{
    uint8_t output[CRYPT_H6_OUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicH6(H6_SPEC_W, CRYPT_H6_KEYID_LEBR, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, H6_LEBR_EXPECT, CRYPT_H6_OUT_LEN));
}

/**
 * @tc.number: StackSmp_H6_KeyIdTmp1Tmp2_00100
 * @tc.name: SMP_CryptographicH6 with keyID "tmp1" and "tmp2"
 * @tc.desc: spec 2.2.10, vectors computed by independent standard AES-CMAC
 */
HWTEST_F(StackSmpToolTest, StackSmp_H6_KeyIdTmp1Tmp2_00100, TestSize.Level1)
{
    uint8_t output[CRYPT_H6_OUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicH6(H6_SPEC_W, CRYPT_H6_KEYID_TMP1, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, H6_TMP1_EXPECT, CRYPT_H6_OUT_LEN));

    ASSERT_EQ(SecureZero(output, sizeof(output)), EOK);
    ASSERT_EQ(SMP_CryptographicH6(H6_SPEC_W, CRYPT_H6_KEYID_TMP2, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, H6_TMP2_EXPECT, CRYPT_H6_OUT_LEN));
}

/**
 * @tc.number: StackSmp_H6_KeyIdBrle_00100
 * @tc.name: SMP_CryptographicH6 with keyID "brle"
 * @tc.desc: spec 2.2.10, regression test for the "brie" typo bug
 */
HWTEST_F(StackSmpToolTest, StackSmp_H6_KeyIdBrle_00100, TestSize.Level1)
{
    uint8_t output[CRYPT_H6_OUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicH6(H6_SPEC_W, CRYPT_H6_KEYID_BRLE, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, H6_BRLE_EXPECT, CRYPT_H6_OUT_LEN));
}

/**
 * @tc.number: StackSmp_H6_NullParam_00100
 * @tc.name: SMP_CryptographicH6 null parameter check
 * @tc.desc: any of w/keyId/output is nullptr should return BT_BAD_PARAM
 */
HWTEST_F(StackSmpToolTest, StackSmp_H6_NullParam_00100, TestSize.Level1)
{
    uint8_t output[CRYPT_H6_OUT_LEN] = {0};
    EXPECT_EQ(SMP_CryptographicH6(nullptr, CRYPT_H6_KEYID_LEBR, output), BT_BAD_PARAM);
    EXPECT_EQ(SMP_CryptographicH6(H6_SPEC_W, nullptr, output), BT_BAD_PARAM);
    EXPECT_EQ(SMP_CryptographicH6(H6_SPEC_W, CRYPT_H6_KEYID_LEBR, nullptr), BT_BAD_PARAM);
}

/**
 * @tc.number: StackSmp_H7_SpecD8_00100
 * @tc.name: SMP_CryptographicH7 with SALT mapped from "tmp1"
 * @tc.desc: spec Vol 3 Part H 2.2.11, Appendix D.8 official vector
 */
HWTEST_F(StackSmpToolTest, StackSmp_H7_SpecD8_00100, TestSize.Level1)
{
    uint8_t output[CRYPT_H7_OUT_LEN] = {0};
    ASSERT_EQ(SMP_CryptographicH7(H7_SPEC_SALT, H6_SPEC_W, output), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(output, H7_EXPECT, CRYPT_H7_OUT_LEN));
}

/**
 * @tc.number: StackSmp_H7_NullParam_00100
 * @tc.name: SMP_CryptographicH7 null parameter check
 * @tc.desc: any of salt/w/output is nullptr should return BT_BAD_PARAM
 */
HWTEST_F(StackSmpToolTest, StackSmp_H7_NullParam_00100, TestSize.Level1)
{
    uint8_t output[CRYPT_H7_OUT_LEN] = {0};
    EXPECT_EQ(SMP_CryptographicH7(nullptr, H6_SPEC_W, output), BT_BAD_PARAM);
    EXPECT_EQ(SMP_CryptographicH7(H7_SPEC_SALT, nullptr, output), BT_BAD_PARAM);
    EXPECT_EQ(SMP_CryptographicH7(H7_SPEC_SALT, H6_SPEC_W, nullptr), BT_BAD_PARAM);
}

/**
 * @tc.number: StackSmp_H6_AliasBuffer_00100
 * @tc.name: SMP_CryptographicH6 input/output alias check
 * @tc.desc: output buffer may alias the input key buffer; result must still match expected
 */
HWTEST_F(StackSmpToolTest, StackSmp_H6_AliasBuffer_00100, TestSize.Level1)
{
    uint8_t aliasBuf[CRYPT_H6_OUT_LEN] = {0};
    ASSERT_EQ(memcpy_s(aliasBuf, sizeof(aliasBuf), H6_SPEC_W, sizeof(H6_SPEC_W)), EOK);
    ASSERT_EQ(SMP_CryptographicH6(aliasBuf, CRYPT_H6_KEYID_LEBR, aliasBuf), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(aliasBuf, H6_LEBR_EXPECT, CRYPT_H6_OUT_LEN));
}

/**
 * @tc.number: StackSmp_H7_AliasBuffer_00100
 * @tc.name: SMP_CryptographicH7 input/output alias check
 * @tc.desc: output buffer may alias the input w buffer; result must still match expected
 */
HWTEST_F(StackSmpToolTest, StackSmp_H7_AliasBuffer_00100, TestSize.Level1)
{
    uint8_t aliasBuf[CRYPT_H7_OUT_LEN] = {0};
    ASSERT_EQ(memcpy_s(aliasBuf, sizeof(aliasBuf), H6_SPEC_W, sizeof(H6_SPEC_W)), EOK);
    ASSERT_EQ(SMP_CryptographicH7(H7_SPEC_SALT, aliasBuf, aliasBuf), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(aliasBuf, H7_EXPECT, CRYPT_H7_OUT_LEN));
}

/**
 * @tc.number: StackSmp_Ctkd_LeToBrEdr_00100
 * @tc.name: SMP_DeriveBredrLinkKeyFromLeLtk
 * @tc.desc: spec Appendix D.10 (CT2=0): ILK = h6(LTK, "tmp1"), link key = h6(ILK, "lebr")
 */
HWTEST_F(StackSmpToolTest, StackSmp_Ctkd_LeToBrEdr_00100, TestSize.Level1)
{
    uint8_t linkKey[CRYPT_H6_OUT_LEN] = {0};
    ASSERT_EQ(SMP_DeriveBredrLinkKeyFromLeLtk(CTKD_D10_LTK, sizeof(CTKD_D10_LTK), linkKey, sizeof(linkKey)),
              BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(linkKey, CTKD_D10_LINK_KEY_EXPECT, CRYPT_H6_OUT_LEN));
}

/**
 * @tc.number: StackSmp_Ctkd_BrEdrToLe_00100
 * @tc.name: SMP_DeriveLeLtkFromBredrLinkKey
 * @tc.desc: spec Appendix D.12 (CT2=0): ILK = h6(link key, "tmp2"), LTK = h6(ILK, "brle")
 */
HWTEST_F(StackSmpToolTest, StackSmp_Ctkd_BrEdrToLe_00100, TestSize.Level1)
{
    uint8_t ltk[CRYPT_H6_OUT_LEN] = {0};
    ASSERT_EQ(SMP_DeriveLeLtkFromBredrLinkKey(CTKD_D12_LINK_KEY, sizeof(CTKD_D12_LINK_KEY), ltk, sizeof(ltk)),
              BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(ltk, CTKD_D12_LTK_EXPECT, CRYPT_H6_OUT_LEN));
}

/**
 * @tc.number: StackSmp_Ctkd_NullParam_00100
 * @tc.name: CTKD derive functions null parameter check
 * @tc.desc: any input/output is nullptr should return BT_BAD_PARAM
 */
HWTEST_F(StackSmpToolTest, StackSmp_Ctkd_NullParam_00100, TestSize.Level1)
{
    uint8_t out[CRYPT_H6_OUT_LEN] = {0};
    EXPECT_EQ(SMP_DeriveBredrLinkKeyFromLeLtk(nullptr, sizeof(CTKD_D10_LTK), out, sizeof(out)), BT_BAD_PARAM);
    EXPECT_EQ(SMP_DeriveBredrLinkKeyFromLeLtk(CTKD_D10_LTK, sizeof(CTKD_D10_LTK), nullptr, sizeof(out)), BT_BAD_PARAM);
    EXPECT_EQ(SMP_DeriveBredrLinkKeyFromLeLtk(CTKD_D10_LTK, CRYPT_H6_OUT_LEN - 1, out, sizeof(out)), BT_BAD_PARAM);
    EXPECT_EQ(SMP_DeriveBredrLinkKeyFromLeLtk(CTKD_D10_LTK, sizeof(CTKD_D10_LTK), out, CRYPT_H6_OUT_LEN - 1),
              BT_BAD_PARAM);

    EXPECT_EQ(SMP_DeriveLeLtkFromBredrLinkKey(nullptr, sizeof(CTKD_D12_LINK_KEY), out, sizeof(out)), BT_BAD_PARAM);
    EXPECT_EQ(SMP_DeriveLeLtkFromBredrLinkKey(CTKD_D12_LINK_KEY, sizeof(CTKD_D12_LINK_KEY), nullptr, sizeof(out)),
              BT_BAD_PARAM);
    EXPECT_EQ(SMP_DeriveLeLtkFromBredrLinkKey(CTKD_D12_LINK_KEY, CRYPT_H6_OUT_LEN - 1, out, sizeof(out)), BT_BAD_PARAM);
    EXPECT_EQ(SMP_DeriveLeLtkFromBredrLinkKey(CTKD_D12_LINK_KEY, sizeof(CTKD_D12_LINK_KEY), out, CRYPT_H6_OUT_LEN - 1),
              BT_BAD_PARAM);
}

/**
 * @tc.number: StackSmp_Ctkd_AliasBuffer_00100
 * @tc.name: CTKD derive functions alias buffer check
 * @tc.desc: input and output buffers may alias each other; a local copy is used internally
 */
HWTEST_F(StackSmpToolTest, StackSmp_Ctkd_AliasBuffer_00100, TestSize.Level1)
{
    uint8_t aliasBuf[CRYPT_H6_OUT_LEN] = {0};
    ASSERT_EQ(memcpy_s(aliasBuf, sizeof(aliasBuf), CTKD_D10_LTK, sizeof(CTKD_D10_LTK)), EOK);
    EXPECT_EQ(SMP_DeriveBredrLinkKeyFromLeLtk(aliasBuf, sizeof(aliasBuf), aliasBuf, sizeof(aliasBuf)), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(aliasBuf, CTKD_D10_LINK_KEY_EXPECT, CRYPT_H6_OUT_LEN));

    ASSERT_EQ(memset_s(aliasBuf, sizeof(aliasBuf), 0, sizeof(aliasBuf)), EOK);
    ASSERT_EQ(memcpy_s(aliasBuf, sizeof(aliasBuf), CTKD_D12_LINK_KEY, sizeof(CTKD_D12_LINK_KEY)), EOK);
    EXPECT_EQ(SMP_DeriveLeLtkFromBredrLinkKey(aliasBuf, sizeof(aliasBuf), aliasBuf, sizeof(aliasBuf)), BT_SUCCESS);
    EXPECT_TRUE(ExpectBytesEq(aliasBuf, CTKD_D12_LTK_EXPECT, CRYPT_H6_OUT_LEN));
}
} // namespace Bluetooth
} // namespace OHOS
