/**
 * Copyright (C) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** apitest 分段1b：Access + Legacy + Profile */
import bluetoothFullCoverageAccess01_p1 from './BluetoothFullCoverageAccess01_p1.test'
import bluetoothFullCoverageAccess01_p2 from './BluetoothFullCoverageAccess01_p2.test'
import bluetoothFullCoverageAccess01_p3 from './BluetoothFullCoverageAccess01_p3.test'
import bluetoothFullCoverageLegacy01_p1 from './BluetoothFullCoverageLegacy01_p1.test'
import bluetoothFullCoverageLegacy01_p2 from './BluetoothFullCoverageLegacy01_p2.test'
import bluetoothFullCoverageLegacy01_p3 from './BluetoothFullCoverageLegacy01_p3.test'
import bluetoothFullCoverageLegacy02_p1 from './BluetoothFullCoverageLegacy02_p1.test'
import bluetoothFullCoverageLegacy02_p2 from './BluetoothFullCoverageLegacy02_p2.test'
import bluetoothFullCoverageLegacy02_p3 from './BluetoothFullCoverageLegacy02_p3.test'
import bluetoothFullCoverageLegacy02_p4 from './BluetoothFullCoverageLegacy02_p4.test'
import bluetoothFullCoverageLegacy02_p5 from './BluetoothFullCoverageLegacy02_p5.test'
import bluetoothFullCoverageLegacy02_p6 from './BluetoothFullCoverageLegacy02_p6.test'
import bluetoothFullCoverageLegacy02_p7 from './BluetoothFullCoverageLegacy02_p7.test'
import bluetoothFullCoverageProfile01_p1 from './BluetoothFullCoverageProfile01_p1.test'
import bluetoothFullCoverageProfile01_p2 from './BluetoothFullCoverageProfile01_p2.test'
import bluetoothFullCoverageProfile01_p3 from './BluetoothFullCoverageProfile01_p3.test'
import bluetoothFullCoverageProfile01_p4 from './BluetoothFullCoverageProfile01_p4.test'
import bluetoothFullCoverageProfile02_p1 from './BluetoothFullCoverageProfile02_p1.test'
import bluetoothFullCoverageProfile02_p2 from './BluetoothFullCoverageProfile02_p2.test'
import bluetoothFullCoverageProfile02_p3 from './BluetoothFullCoverageProfile02_p3.test'
import bluetoothFullCoverageProfile02_p4 from './BluetoothFullCoverageProfile02_p4.test'
import bluetoothFullCoverageProfile02_p5 from './BluetoothFullCoverageProfile02_p5.test'
import bluetoothFullCoverageProfile02_p6 from './BluetoothFullCoverageProfile02_p6.test'
export default function testsuiteApitestPart1b(): void {
  bluetoothFullCoverageAccess01_p1()
  bluetoothFullCoverageAccess01_p2()
  bluetoothFullCoverageAccess01_p3()
  bluetoothFullCoverageLegacy01_p1()
  bluetoothFullCoverageLegacy01_p2()
  bluetoothFullCoverageLegacy01_p3()
  bluetoothFullCoverageLegacy02_p1()
  bluetoothFullCoverageLegacy02_p2()
  bluetoothFullCoverageLegacy02_p3()
  bluetoothFullCoverageLegacy02_p4()
  bluetoothFullCoverageLegacy02_p5()
  bluetoothFullCoverageLegacy02_p6()
  bluetoothFullCoverageLegacy02_p7()
  bluetoothFullCoverageProfile01_p1()
  bluetoothFullCoverageProfile01_p2()
  bluetoothFullCoverageProfile01_p3()
  bluetoothFullCoverageProfile01_p4()
  bluetoothFullCoverageProfile02_p1()
  bluetoothFullCoverageProfile02_p2()
  bluetoothFullCoverageProfile02_p3()
  bluetoothFullCoverageProfile02_p4()
  bluetoothFullCoverageProfile02_p5()
  bluetoothFullCoverageProfile02_p6()
}
